using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GearHub.Api.Migrations;

/// <summary>
/// Upgrades databases created earlier via <c>EnsureCreated()</c> (domain tables already exist)
/// by adding ASP.NET Identity, permissions, and repointing rental orders to <c>AspNetUsers</c>.
/// Safe to re-run after a partial failed apply (uses IF NOT EXISTS / IF EXISTS).
/// </summary>
public partial class AddIdentityAndPermissions : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            -- Legacy Identity tables from a failed partial migration are dropped and recreated below.

            CREATE TABLE IF NOT EXISTS "AspNetRoles" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" character varying(256),
                "NormalizedName" character varying(256),
                "ConcurrencyStamp" text,
                CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "AspNetUsers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "DisplayName" text NOT NULL DEFAULT '',
                "UserName" character varying(256),
                "NormalizedUserName" character varying(256),
                "Email" character varying(256),
                "NormalizedEmail" character varying(256),
                "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
                "PasswordHash" text,
                "SecurityStamp" text,
                "ConcurrencyStamp" text,
                "PhoneNumber" text,
                "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE,
                "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
                "LockoutEnd" timestamp with time zone,
                "LockoutEnabled" boolean NOT NULL DEFAULT FALSE,
                "AccessFailedCount" integer NOT NULL DEFAULT 0,
                CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "RoleId" integer NOT NULL,
                "ClaimType" text,
                "ClaimValue" text,
                CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
                    REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" integer NOT NULL,
                "ClaimType" text,
                "ClaimValue" text,
                CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
                    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
                "LoginProvider" text NOT NULL,
                "ProviderKey" text NOT NULL,
                "ProviderDisplayName" text,
                "UserId" integer NOT NULL,
                CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
                    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
                "UserId" integer NOT NULL,
                "RoleId" integer NOT NULL,
                CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
                    REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
                    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
                "UserId" integer NOT NULL,
                "LoginProvider" text NOT NULL,
                "Name" text NOT NULL,
                "Value" text,
                CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
                    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "Permissions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" text NOT NULL,
                "Description" text NOT NULL,
                CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "RolePermissions" (
                "RoleId" integer NOT NULL,
                "PermissionId" integer NOT NULL,
                CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
                CONSTRAINT "FK_RolePermissions_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
                    REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId")
                    REFERENCES "Permissions" ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
            CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
            CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
            CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
            CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
            CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
            CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Permissions_Name" ON "Permissions" ("Name");
            CREATE INDEX IF NOT EXISTS "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");

            -- Drop legacy user tables; no data migration (Identity users are seeded on app startup).
            ALTER TABLE "RentalOrders" DROP CONSTRAINT IF EXISTS "FK_RentalOrders_Users_UserId";

            DELETE FROM "RentalOrderItems";
            DELETE FROM "RentalOrders";

            DO $rep$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_RentalOrders_AspNetUsers_UserId'
                ) THEN
                    ALTER TABLE "RentalOrders"
                        ADD CONSTRAINT "FK_RentalOrders_AspNetUsers_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;
                END IF;
            END
            $rep$;

            DROP TABLE IF EXISTS "Users";
            DROP TABLE IF EXISTS "Roles";
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            ALTER TABLE "RentalOrders" DROP CONSTRAINT IF EXISTS "FK_RentalOrders_AspNetUsers_UserId";

            DROP TABLE IF EXISTS "RolePermissions";
            DROP TABLE IF EXISTS "Permissions";
            DROP TABLE IF EXISTS "AspNetUserTokens";
            DROP TABLE IF EXISTS "AspNetUserRoles";
            DROP TABLE IF EXISTS "AspNetUserLogins";
            DROP TABLE IF EXISTS "AspNetUserClaims";
            DROP TABLE IF EXISTS "AspNetRoleClaims";
            DROP TABLE IF EXISTS "AspNetUsers";
            DROP TABLE IF EXISTS "AspNetRoles";
            """);
    }
}
