/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as IntranetRouteRouteImport } from './routes/intranet/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as IntranetIndexRouteImport } from './routes/intranet/index'
import { Route as PortalCartRouteImport } from './routes/portal/cart'
import { Route as IntranetWarehousesRouteImport } from './routes/intranet/warehouses'
import { Route as IntranetUsersRouteImport } from './routes/intranet/users'
import { Route as IntranetMaintenanceRouteImport } from './routes/intranet/maintenance'
import { Route as IntranetCustomersRouteImport } from './routes/intranet/customers'
import { Route as IntranetCategoriesRouteImport } from './routes/intranet/categories'
import { Route as IntranetBrandsRouteImport } from './routes/intranet/brands'
import { Route as PortalNewsRouteRouteImport } from './routes/portal/news/route'
import { Route as IntranetPortalTextsRouteRouteImport } from './routes/intranet/portal-texts/route'
import { Route as IntranetOrdersRouteRouteImport } from './routes/intranet/orders/route'
import { Route as IntranetEquipmentRouteRouteImport } from './routes/intranet/equipment/route'
import { Route as PortalNewsIndexRouteImport } from './routes/portal/news/index'
import { Route as IntranetPortalTextsIndexRouteImport } from './routes/intranet/portal-texts/index'
import { Route as IntranetOrdersIndexRouteImport } from './routes/intranet/orders/index'
import { Route as IntranetEquipmentIndexRouteImport } from './routes/intranet/equipment/index'
import { Route as PortalNewsSlugRouteImport } from './routes/portal/news/$slug'
import { Route as PortalEquipmentEquipmentIdRouteImport } from './routes/portal/equipment/$equipmentId'
import { Route as IntranetPortalTextsNewRouteImport } from './routes/intranet/portal-texts/new'
import { Route as IntranetOrdersOrderIdRouteImport } from './routes/intranet/orders/$orderId'
import { Route as IntranetEquipmentNewRouteImport } from './routes/intranet/equipment/new'
import { Route as IntranetPortalTextsPostIdEditRouteImport } from './routes/intranet/portal-texts/$postId/edit'
import { Route as IntranetEquipmentEquipmentIdEditRouteImport } from './routes/intranet/equipment/$equipmentId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntranetRouteRoute = IntranetRouteRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const IntranetIndexRoute = IntranetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const PortalCartRoute = PortalCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PortalRouteRoute,
} as any)
const IntranetWarehousesRoute = IntranetWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetUsersRoute = IntranetUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetMaintenanceRoute = IntranetMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetCustomersRoute = IntranetCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetCategoriesRoute = IntranetCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetBrandsRoute = IntranetBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const PortalNewsRouteRoute = PortalNewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PortalRouteRoute,
} as any)
const IntranetPortalTextsRouteRoute =
  IntranetPortalTextsRouteRouteImport.update({
    id: '/portal-texts',
    path: '/portal-texts',
    getParentRoute: () => IntranetRouteRoute,
  } as any)
const IntranetOrdersRouteRoute = IntranetOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetEquipmentRouteRoute = IntranetEquipmentRouteRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const PortalNewsIndexRoute = PortalNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalNewsRouteRoute,
} as any)
const IntranetPortalTextsIndexRoute =
  IntranetPortalTextsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IntranetPortalTextsRouteRoute,
  } as any)
const IntranetOrdersIndexRoute = IntranetOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntranetOrdersRouteRoute,
} as any)
const IntranetEquipmentIndexRoute = IntranetEquipmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntranetEquipmentRouteRoute,
} as any)
const PortalNewsSlugRoute = PortalNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortalNewsRouteRoute,
} as any)
const PortalEquipmentEquipmentIdRoute =
  PortalEquipmentEquipmentIdRouteImport.update({
    id: '/equipment/$equipmentId',
    path: '/equipment/$equipmentId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const IntranetPortalTextsNewRoute = IntranetPortalTextsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IntranetPortalTextsRouteRoute,
} as any)
const IntranetOrdersOrderIdRoute = IntranetOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => IntranetOrdersRouteRoute,
} as any)
const IntranetEquipmentNewRoute = IntranetEquipmentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IntranetEquipmentRouteRoute,
} as any)
const IntranetPortalTextsPostIdEditRoute =
  IntranetPortalTextsPostIdEditRouteImport.update({
    id: '/$postId/edit',
    path: '/$postId/edit',
    getParentRoute: () => IntranetPortalTextsRouteRoute,
  } as any)
const IntranetEquipmentEquipmentIdEditRoute =
  IntranetEquipmentEquipmentIdEditRouteImport.update({
    id: '/$equipmentId/edit',
    path: '/$equipmentId/edit',
    getParentRoute: () => IntranetEquipmentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intranet': typeof IntranetRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/intranet/equipment': typeof IntranetEquipmentRouteRouteWithChildren
  '/intranet/orders': typeof IntranetOrdersRouteRouteWithChildren
  '/intranet/portal-texts': typeof IntranetPortalTextsRouteRouteWithChildren
  '/portal/news': typeof PortalNewsRouteRouteWithChildren
  '/intranet/brands': typeof IntranetBrandsRoute
  '/intranet/categories': typeof IntranetCategoriesRoute
  '/intranet/customers': typeof IntranetCustomersRoute
  '/intranet/maintenance': typeof IntranetMaintenanceRoute
  '/intranet/users': typeof IntranetUsersRoute
  '/intranet/warehouses': typeof IntranetWarehousesRoute
  '/portal/cart': typeof PortalCartRoute
  '/intranet/': typeof IntranetIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/intranet/equipment/new': typeof IntranetEquipmentNewRoute
  '/intranet/orders/$orderId': typeof IntranetOrdersOrderIdRoute
  '/intranet/portal-texts/new': typeof IntranetPortalTextsNewRoute
  '/portal/equipment/$equipmentId': typeof PortalEquipmentEquipmentIdRoute
  '/portal/news/$slug': typeof PortalNewsSlugRoute
  '/intranet/equipment/': typeof IntranetEquipmentIndexRoute
  '/intranet/orders/': typeof IntranetOrdersIndexRoute
  '/intranet/portal-texts/': typeof IntranetPortalTextsIndexRoute
  '/portal/news/': typeof PortalNewsIndexRoute
  '/intranet/equipment/$equipmentId/edit': typeof IntranetEquipmentEquipmentIdEditRoute
  '/intranet/portal-texts/$postId/edit': typeof IntranetPortalTextsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/intranet/brands': typeof IntranetBrandsRoute
  '/intranet/categories': typeof IntranetCategoriesRoute
  '/intranet/customers': typeof IntranetCustomersRoute
  '/intranet/maintenance': typeof IntranetMaintenanceRoute
  '/intranet/users': typeof IntranetUsersRoute
  '/intranet/warehouses': typeof IntranetWarehousesRoute
  '/portal/cart': typeof PortalCartRoute
  '/intranet': typeof IntranetIndexRoute
  '/portal': typeof PortalIndexRoute
  '/intranet/equipment/new': typeof IntranetEquipmentNewRoute
  '/intranet/orders/$orderId': typeof IntranetOrdersOrderIdRoute
  '/intranet/portal-texts/new': typeof IntranetPortalTextsNewRoute
  '/portal/equipment/$equipmentId': typeof PortalEquipmentEquipmentIdRoute
  '/portal/news/$slug': typeof PortalNewsSlugRoute
  '/intranet/equipment': typeof IntranetEquipmentIndexRoute
  '/intranet/orders': typeof IntranetOrdersIndexRoute
  '/intranet/portal-texts': typeof IntranetPortalTextsIndexRoute
  '/portal/news': typeof PortalNewsIndexRoute
  '/intranet/equipment/$equipmentId/edit': typeof IntranetEquipmentEquipmentIdEditRoute
  '/intranet/portal-texts/$postId/edit': typeof IntranetPortalTextsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intranet': typeof IntranetRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/intranet/equipment': typeof IntranetEquipmentRouteRouteWithChildren
  '/intranet/orders': typeof IntranetOrdersRouteRouteWithChildren
  '/intranet/portal-texts': typeof IntranetPortalTextsRouteRouteWithChildren
  '/portal/news': typeof PortalNewsRouteRouteWithChildren
  '/intranet/brands': typeof IntranetBrandsRoute
  '/intranet/categories': typeof IntranetCategoriesRoute
  '/intranet/customers': typeof IntranetCustomersRoute
  '/intranet/maintenance': typeof IntranetMaintenanceRoute
  '/intranet/users': typeof IntranetUsersRoute
  '/intranet/warehouses': typeof IntranetWarehousesRoute
  '/portal/cart': typeof PortalCartRoute
  '/intranet/': typeof IntranetIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/intranet/equipment/new': typeof IntranetEquipmentNewRoute
  '/intranet/orders/$orderId': typeof IntranetOrdersOrderIdRoute
  '/intranet/portal-texts/new': typeof IntranetPortalTextsNewRoute
  '/portal/equipment/$equipmentId': typeof PortalEquipmentEquipmentIdRoute
  '/portal/news/$slug': typeof PortalNewsSlugRoute
  '/intranet/equipment/': typeof IntranetEquipmentIndexRoute
  '/intranet/orders/': typeof IntranetOrdersIndexRoute
  '/intranet/portal-texts/': typeof IntranetPortalTextsIndexRoute
  '/portal/news/': typeof PortalNewsIndexRoute
  '/intranet/equipment/$equipmentId/edit': typeof IntranetEquipmentEquipmentIdEditRoute
  '/intranet/portal-texts/$postId/edit': typeof IntranetPortalTextsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intranet'
    | '/portal'
    | '/login'
    | '/register'
    | '/intranet/equipment'
    | '/intranet/orders'
    | '/intranet/portal-texts'
    | '/portal/news'
    | '/intranet/brands'
    | '/intranet/categories'
    | '/intranet/customers'
    | '/intranet/maintenance'
    | '/intranet/users'
    | '/intranet/warehouses'
    | '/portal/cart'
    | '/intranet/'
    | '/portal/'
    | '/intranet/equipment/new'
    | '/intranet/orders/$orderId'
    | '/intranet/portal-texts/new'
    | '/portal/equipment/$equipmentId'
    | '/portal/news/$slug'
    | '/intranet/equipment/'
    | '/intranet/orders/'
    | '/intranet/portal-texts/'
    | '/portal/news/'
    | '/intranet/equipment/$equipmentId/edit'
    | '/intranet/portal-texts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/intranet/brands'
    | '/intranet/categories'
    | '/intranet/customers'
    | '/intranet/maintenance'
    | '/intranet/users'
    | '/intranet/warehouses'
    | '/portal/cart'
    | '/intranet'
    | '/portal'
    | '/intranet/equipment/new'
    | '/intranet/orders/$orderId'
    | '/intranet/portal-texts/new'
    | '/portal/equipment/$equipmentId'
    | '/portal/news/$slug'
    | '/intranet/equipment'
    | '/intranet/orders'
    | '/intranet/portal-texts'
    | '/portal/news'
    | '/intranet/equipment/$equipmentId/edit'
    | '/intranet/portal-texts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/intranet'
    | '/portal'
    | '/login'
    | '/register'
    | '/intranet/equipment'
    | '/intranet/orders'
    | '/intranet/portal-texts'
    | '/portal/news'
    | '/intranet/brands'
    | '/intranet/categories'
    | '/intranet/customers'
    | '/intranet/maintenance'
    | '/intranet/users'
    | '/intranet/warehouses'
    | '/portal/cart'
    | '/intranet/'
    | '/portal/'
    | '/intranet/equipment/new'
    | '/intranet/orders/$orderId'
    | '/intranet/portal-texts/new'
    | '/portal/equipment/$equipmentId'
    | '/portal/news/$slug'
    | '/intranet/equipment/'
    | '/intranet/orders/'
    | '/intranet/portal-texts/'
    | '/portal/news/'
    | '/intranet/equipment/$equipmentId/edit'
    | '/intranet/portal-texts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntranetRouteRoute: typeof IntranetRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet': {
      id: '/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/intranet/': {
      id: '/intranet/'
      path: '/'
      fullPath: '/intranet/'
      preLoaderRoute: typeof IntranetIndexRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/portal/cart': {
      id: '/portal/cart'
      path: '/cart'
      fullPath: '/portal/cart'
      preLoaderRoute: typeof PortalCartRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/intranet/warehouses': {
      id: '/intranet/warehouses'
      path: '/warehouses'
      fullPath: '/intranet/warehouses'
      preLoaderRoute: typeof IntranetWarehousesRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/users': {
      id: '/intranet/users'
      path: '/users'
      fullPath: '/intranet/users'
      preLoaderRoute: typeof IntranetUsersRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/maintenance': {
      id: '/intranet/maintenance'
      path: '/maintenance'
      fullPath: '/intranet/maintenance'
      preLoaderRoute: typeof IntranetMaintenanceRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/customers': {
      id: '/intranet/customers'
      path: '/customers'
      fullPath: '/intranet/customers'
      preLoaderRoute: typeof IntranetCustomersRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/categories': {
      id: '/intranet/categories'
      path: '/categories'
      fullPath: '/intranet/categories'
      preLoaderRoute: typeof IntranetCategoriesRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/brands': {
      id: '/intranet/brands'
      path: '/brands'
      fullPath: '/intranet/brands'
      preLoaderRoute: typeof IntranetBrandsRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/portal/news': {
      id: '/portal/news'
      path: '/news'
      fullPath: '/portal/news'
      preLoaderRoute: typeof PortalNewsRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/intranet/portal-texts': {
      id: '/intranet/portal-texts'
      path: '/portal-texts'
      fullPath: '/intranet/portal-texts'
      preLoaderRoute: typeof IntranetPortalTextsRouteRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/orders': {
      id: '/intranet/orders'
      path: '/orders'
      fullPath: '/intranet/orders'
      preLoaderRoute: typeof IntranetOrdersRouteRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/equipment': {
      id: '/intranet/equipment'
      path: '/equipment'
      fullPath: '/intranet/equipment'
      preLoaderRoute: typeof IntranetEquipmentRouteRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/portal/news/': {
      id: '/portal/news/'
      path: '/'
      fullPath: '/portal/news/'
      preLoaderRoute: typeof PortalNewsIndexRouteImport
      parentRoute: typeof PortalNewsRouteRoute
    }
    '/intranet/portal-texts/': {
      id: '/intranet/portal-texts/'
      path: '/'
      fullPath: '/intranet/portal-texts/'
      preLoaderRoute: typeof IntranetPortalTextsIndexRouteImport
      parentRoute: typeof IntranetPortalTextsRouteRoute
    }
    '/intranet/orders/': {
      id: '/intranet/orders/'
      path: '/'
      fullPath: '/intranet/orders/'
      preLoaderRoute: typeof IntranetOrdersIndexRouteImport
      parentRoute: typeof IntranetOrdersRouteRoute
    }
    '/intranet/equipment/': {
      id: '/intranet/equipment/'
      path: '/'
      fullPath: '/intranet/equipment/'
      preLoaderRoute: typeof IntranetEquipmentIndexRouteImport
      parentRoute: typeof IntranetEquipmentRouteRoute
    }
    '/portal/news/$slug': {
      id: '/portal/news/$slug'
      path: '/$slug'
      fullPath: '/portal/news/$slug'
      preLoaderRoute: typeof PortalNewsSlugRouteImport
      parentRoute: typeof PortalNewsRouteRoute
    }
    '/portal/equipment/$equipmentId': {
      id: '/portal/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/portal/equipment/$equipmentId'
      preLoaderRoute: typeof PortalEquipmentEquipmentIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/intranet/portal-texts/new': {
      id: '/intranet/portal-texts/new'
      path: '/new'
      fullPath: '/intranet/portal-texts/new'
      preLoaderRoute: typeof IntranetPortalTextsNewRouteImport
      parentRoute: typeof IntranetPortalTextsRouteRoute
    }
    '/intranet/orders/$orderId': {
      id: '/intranet/orders/$orderId'
      path: '/$orderId'
      fullPath: '/intranet/orders/$orderId'
      preLoaderRoute: typeof IntranetOrdersOrderIdRouteImport
      parentRoute: typeof IntranetOrdersRouteRoute
    }
    '/intranet/equipment/new': {
      id: '/intranet/equipment/new'
      path: '/new'
      fullPath: '/intranet/equipment/new'
      preLoaderRoute: typeof IntranetEquipmentNewRouteImport
      parentRoute: typeof IntranetEquipmentRouteRoute
    }
    '/intranet/portal-texts/$postId/edit': {
      id: '/intranet/portal-texts/$postId/edit'
      path: '/$postId/edit'
      fullPath: '/intranet/portal-texts/$postId/edit'
      preLoaderRoute: typeof IntranetPortalTextsPostIdEditRouteImport
      parentRoute: typeof IntranetPortalTextsRouteRoute
    }
    '/intranet/equipment/$equipmentId/edit': {
      id: '/intranet/equipment/$equipmentId/edit'
      path: '/$equipmentId/edit'
      fullPath: '/intranet/equipment/$equipmentId/edit'
      preLoaderRoute: typeof IntranetEquipmentEquipmentIdEditRouteImport
      parentRoute: typeof IntranetEquipmentRouteRoute
    }
  }
}

interface IntranetEquipmentRouteRouteChildren {
  IntranetEquipmentNewRoute: typeof IntranetEquipmentNewRoute
  IntranetEquipmentIndexRoute: typeof IntranetEquipmentIndexRoute
  IntranetEquipmentEquipmentIdEditRoute: typeof IntranetEquipmentEquipmentIdEditRoute
}

const IntranetEquipmentRouteRouteChildren: IntranetEquipmentRouteRouteChildren =
  {
    IntranetEquipmentNewRoute: IntranetEquipmentNewRoute,
    IntranetEquipmentIndexRoute: IntranetEquipmentIndexRoute,
    IntranetEquipmentEquipmentIdEditRoute:
      IntranetEquipmentEquipmentIdEditRoute,
  }

const IntranetEquipmentRouteRouteWithChildren =
  IntranetEquipmentRouteRoute._addFileChildren(
    IntranetEquipmentRouteRouteChildren,
  )

interface IntranetOrdersRouteRouteChildren {
  IntranetOrdersOrderIdRoute: typeof IntranetOrdersOrderIdRoute
  IntranetOrdersIndexRoute: typeof IntranetOrdersIndexRoute
}

const IntranetOrdersRouteRouteChildren: IntranetOrdersRouteRouteChildren = {
  IntranetOrdersOrderIdRoute: IntranetOrdersOrderIdRoute,
  IntranetOrdersIndexRoute: IntranetOrdersIndexRoute,
}

const IntranetOrdersRouteRouteWithChildren =
  IntranetOrdersRouteRoute._addFileChildren(IntranetOrdersRouteRouteChildren)

interface IntranetPortalTextsRouteRouteChildren {
  IntranetPortalTextsNewRoute: typeof IntranetPortalTextsNewRoute
  IntranetPortalTextsIndexRoute: typeof IntranetPortalTextsIndexRoute
  IntranetPortalTextsPostIdEditRoute: typeof IntranetPortalTextsPostIdEditRoute
}

const IntranetPortalTextsRouteRouteChildren: IntranetPortalTextsRouteRouteChildren =
  {
    IntranetPortalTextsNewRoute: IntranetPortalTextsNewRoute,
    IntranetPortalTextsIndexRoute: IntranetPortalTextsIndexRoute,
    IntranetPortalTextsPostIdEditRoute: IntranetPortalTextsPostIdEditRoute,
  }

const IntranetPortalTextsRouteRouteWithChildren =
  IntranetPortalTextsRouteRoute._addFileChildren(
    IntranetPortalTextsRouteRouteChildren,
  )

interface IntranetRouteRouteChildren {
  IntranetEquipmentRouteRoute: typeof IntranetEquipmentRouteRouteWithChildren
  IntranetOrdersRouteRoute: typeof IntranetOrdersRouteRouteWithChildren
  IntranetPortalTextsRouteRoute: typeof IntranetPortalTextsRouteRouteWithChildren
  IntranetBrandsRoute: typeof IntranetBrandsRoute
  IntranetCategoriesRoute: typeof IntranetCategoriesRoute
  IntranetCustomersRoute: typeof IntranetCustomersRoute
  IntranetMaintenanceRoute: typeof IntranetMaintenanceRoute
  IntranetUsersRoute: typeof IntranetUsersRoute
  IntranetWarehousesRoute: typeof IntranetWarehousesRoute
  IntranetIndexRoute: typeof IntranetIndexRoute
}

const IntranetRouteRouteChildren: IntranetRouteRouteChildren = {
  IntranetEquipmentRouteRoute: IntranetEquipmentRouteRouteWithChildren,
  IntranetOrdersRouteRoute: IntranetOrdersRouteRouteWithChildren,
  IntranetPortalTextsRouteRoute: IntranetPortalTextsRouteRouteWithChildren,
  IntranetBrandsRoute: IntranetBrandsRoute,
  IntranetCategoriesRoute: IntranetCategoriesRoute,
  IntranetCustomersRoute: IntranetCustomersRoute,
  IntranetMaintenanceRoute: IntranetMaintenanceRoute,
  IntranetUsersRoute: IntranetUsersRoute,
  IntranetWarehousesRoute: IntranetWarehousesRoute,
  IntranetIndexRoute: IntranetIndexRoute,
}

const IntranetRouteRouteWithChildren = IntranetRouteRoute._addFileChildren(
  IntranetRouteRouteChildren,
)

interface PortalNewsRouteRouteChildren {
  PortalNewsSlugRoute: typeof PortalNewsSlugRoute
  PortalNewsIndexRoute: typeof PortalNewsIndexRoute
}

const PortalNewsRouteRouteChildren: PortalNewsRouteRouteChildren = {
  PortalNewsSlugRoute: PortalNewsSlugRoute,
  PortalNewsIndexRoute: PortalNewsIndexRoute,
}

const PortalNewsRouteRouteWithChildren = PortalNewsRouteRoute._addFileChildren(
  PortalNewsRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalNewsRouteRoute: typeof PortalNewsRouteRouteWithChildren
  PortalCartRoute: typeof PortalCartRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalEquipmentEquipmentIdRoute: typeof PortalEquipmentEquipmentIdRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalNewsRouteRoute: PortalNewsRouteRouteWithChildren,
  PortalCartRoute: PortalCartRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalEquipmentEquipmentIdRoute: PortalEquipmentEquipmentIdRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntranetRouteRoute: IntranetRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
