/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as IntranetRouteRouteImport } from './routes/intranet/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as IntranetIndexRouteImport } from './routes/intranet/index'
import { Route as PortalCartRouteImport } from './routes/portal/cart'
import { Route as IntranetWarehousesRouteImport } from './routes/intranet/warehouses'
import { Route as IntranetUsersRouteImport } from './routes/intranet/users'
import { Route as IntranetPortalTextsRouteImport } from './routes/intranet/portal-texts'
import { Route as IntranetOrdersRouteImport } from './routes/intranet/orders'
import { Route as IntranetMaintenanceRouteImport } from './routes/intranet/maintenance'
import { Route as IntranetCustomersRouteImport } from './routes/intranet/customers'
import { Route as IntranetCategoriesRouteImport } from './routes/intranet/categories'
import { Route as IntranetBrandsRouteImport } from './routes/intranet/brands'
import { Route as IntranetEquipmentRouteRouteImport } from './routes/intranet/equipment/route'
import { Route as IntranetEquipmentIndexRouteImport } from './routes/intranet/equipment/index'
import { Route as IntranetEquipmentNewRouteImport } from './routes/intranet/equipment/new'

const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntranetRouteRoute = IntranetRouteRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const IntranetIndexRoute = IntranetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const PortalCartRoute = PortalCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PortalRouteRoute,
} as any)
const IntranetWarehousesRoute = IntranetWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetUsersRoute = IntranetUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetPortalTextsRoute = IntranetPortalTextsRouteImport.update({
  id: '/portal-texts',
  path: '/portal-texts',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetOrdersRoute = IntranetOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetMaintenanceRoute = IntranetMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetCustomersRoute = IntranetCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetCategoriesRoute = IntranetCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetBrandsRoute = IntranetBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetEquipmentRouteRoute = IntranetEquipmentRouteRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => IntranetRouteRoute,
} as any)
const IntranetEquipmentIndexRoute = IntranetEquipmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntranetEquipmentRouteRoute,
} as any)
const IntranetEquipmentNewRoute = IntranetEquipmentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IntranetEquipmentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intranet': typeof IntranetRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/intranet/equipment': typeof IntranetEquipmentRouteRouteWithChildren
  '/intranet/brands': typeof IntranetBrandsRoute
  '/intranet/categories': typeof IntranetCategoriesRoute
  '/intranet/customers': typeof IntranetCustomersRoute
  '/intranet/maintenance': typeof IntranetMaintenanceRoute
  '/intranet/orders': typeof IntranetOrdersRoute
  '/intranet/portal-texts': typeof IntranetPortalTextsRoute
  '/intranet/users': typeof IntranetUsersRoute
  '/intranet/warehouses': typeof IntranetWarehousesRoute
  '/portal/cart': typeof PortalCartRoute
  '/intranet/': typeof IntranetIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/intranet/equipment/new': typeof IntranetEquipmentNewRoute
  '/intranet/equipment/': typeof IntranetEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intranet/brands': typeof IntranetBrandsRoute
  '/intranet/categories': typeof IntranetCategoriesRoute
  '/intranet/customers': typeof IntranetCustomersRoute
  '/intranet/maintenance': typeof IntranetMaintenanceRoute
  '/intranet/orders': typeof IntranetOrdersRoute
  '/intranet/portal-texts': typeof IntranetPortalTextsRoute
  '/intranet/users': typeof IntranetUsersRoute
  '/intranet/warehouses': typeof IntranetWarehousesRoute
  '/portal/cart': typeof PortalCartRoute
  '/intranet': typeof IntranetIndexRoute
  '/portal': typeof PortalIndexRoute
  '/intranet/equipment/new': typeof IntranetEquipmentNewRoute
  '/intranet/equipment': typeof IntranetEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intranet': typeof IntranetRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/intranet/equipment': typeof IntranetEquipmentRouteRouteWithChildren
  '/intranet/brands': typeof IntranetBrandsRoute
  '/intranet/categories': typeof IntranetCategoriesRoute
  '/intranet/customers': typeof IntranetCustomersRoute
  '/intranet/maintenance': typeof IntranetMaintenanceRoute
  '/intranet/orders': typeof IntranetOrdersRoute
  '/intranet/portal-texts': typeof IntranetPortalTextsRoute
  '/intranet/users': typeof IntranetUsersRoute
  '/intranet/warehouses': typeof IntranetWarehousesRoute
  '/portal/cart': typeof PortalCartRoute
  '/intranet/': typeof IntranetIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/intranet/equipment/new': typeof IntranetEquipmentNewRoute
  '/intranet/equipment/': typeof IntranetEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intranet'
    | '/portal'
    | '/intranet/equipment'
    | '/intranet/brands'
    | '/intranet/categories'
    | '/intranet/customers'
    | '/intranet/maintenance'
    | '/intranet/orders'
    | '/intranet/portal-texts'
    | '/intranet/users'
    | '/intranet/warehouses'
    | '/portal/cart'
    | '/intranet/'
    | '/portal/'
    | '/intranet/equipment/new'
    | '/intranet/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intranet/brands'
    | '/intranet/categories'
    | '/intranet/customers'
    | '/intranet/maintenance'
    | '/intranet/orders'
    | '/intranet/portal-texts'
    | '/intranet/users'
    | '/intranet/warehouses'
    | '/portal/cart'
    | '/intranet'
    | '/portal'
    | '/intranet/equipment/new'
    | '/intranet/equipment'
  id:
    | '__root__'
    | '/'
    | '/intranet'
    | '/portal'
    | '/intranet/equipment'
    | '/intranet/brands'
    | '/intranet/categories'
    | '/intranet/customers'
    | '/intranet/maintenance'
    | '/intranet/orders'
    | '/intranet/portal-texts'
    | '/intranet/users'
    | '/intranet/warehouses'
    | '/portal/cart'
    | '/intranet/'
    | '/portal/'
    | '/intranet/equipment/new'
    | '/intranet/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntranetRouteRoute: typeof IntranetRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet': {
      id: '/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/intranet/': {
      id: '/intranet/'
      path: '/'
      fullPath: '/intranet/'
      preLoaderRoute: typeof IntranetIndexRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/portal/cart': {
      id: '/portal/cart'
      path: '/cart'
      fullPath: '/portal/cart'
      preLoaderRoute: typeof PortalCartRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/intranet/warehouses': {
      id: '/intranet/warehouses'
      path: '/warehouses'
      fullPath: '/intranet/warehouses'
      preLoaderRoute: typeof IntranetWarehousesRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/users': {
      id: '/intranet/users'
      path: '/users'
      fullPath: '/intranet/users'
      preLoaderRoute: typeof IntranetUsersRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/portal-texts': {
      id: '/intranet/portal-texts'
      path: '/portal-texts'
      fullPath: '/intranet/portal-texts'
      preLoaderRoute: typeof IntranetPortalTextsRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/orders': {
      id: '/intranet/orders'
      path: '/orders'
      fullPath: '/intranet/orders'
      preLoaderRoute: typeof IntranetOrdersRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/maintenance': {
      id: '/intranet/maintenance'
      path: '/maintenance'
      fullPath: '/intranet/maintenance'
      preLoaderRoute: typeof IntranetMaintenanceRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/customers': {
      id: '/intranet/customers'
      path: '/customers'
      fullPath: '/intranet/customers'
      preLoaderRoute: typeof IntranetCustomersRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/categories': {
      id: '/intranet/categories'
      path: '/categories'
      fullPath: '/intranet/categories'
      preLoaderRoute: typeof IntranetCategoriesRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/brands': {
      id: '/intranet/brands'
      path: '/brands'
      fullPath: '/intranet/brands'
      preLoaderRoute: typeof IntranetBrandsRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/equipment': {
      id: '/intranet/equipment'
      path: '/equipment'
      fullPath: '/intranet/equipment'
      preLoaderRoute: typeof IntranetEquipmentRouteRouteImport
      parentRoute: typeof IntranetRouteRoute
    }
    '/intranet/equipment/': {
      id: '/intranet/equipment/'
      path: '/'
      fullPath: '/intranet/equipment/'
      preLoaderRoute: typeof IntranetEquipmentIndexRouteImport
      parentRoute: typeof IntranetEquipmentRouteRoute
    }
    '/intranet/equipment/new': {
      id: '/intranet/equipment/new'
      path: '/new'
      fullPath: '/intranet/equipment/new'
      preLoaderRoute: typeof IntranetEquipmentNewRouteImport
      parentRoute: typeof IntranetEquipmentRouteRoute
    }
  }
}

interface IntranetEquipmentRouteRouteChildren {
  IntranetEquipmentNewRoute: typeof IntranetEquipmentNewRoute
  IntranetEquipmentIndexRoute: typeof IntranetEquipmentIndexRoute
}

const IntranetEquipmentRouteRouteChildren: IntranetEquipmentRouteRouteChildren =
  {
    IntranetEquipmentNewRoute: IntranetEquipmentNewRoute,
    IntranetEquipmentIndexRoute: IntranetEquipmentIndexRoute,
  }

const IntranetEquipmentRouteRouteWithChildren =
  IntranetEquipmentRouteRoute._addFileChildren(
    IntranetEquipmentRouteRouteChildren,
  )

interface IntranetRouteRouteChildren {
  IntranetEquipmentRouteRoute: typeof IntranetEquipmentRouteRouteWithChildren
  IntranetBrandsRoute: typeof IntranetBrandsRoute
  IntranetCategoriesRoute: typeof IntranetCategoriesRoute
  IntranetCustomersRoute: typeof IntranetCustomersRoute
  IntranetMaintenanceRoute: typeof IntranetMaintenanceRoute
  IntranetOrdersRoute: typeof IntranetOrdersRoute
  IntranetPortalTextsRoute: typeof IntranetPortalTextsRoute
  IntranetUsersRoute: typeof IntranetUsersRoute
  IntranetWarehousesRoute: typeof IntranetWarehousesRoute
  IntranetIndexRoute: typeof IntranetIndexRoute
}

const IntranetRouteRouteChildren: IntranetRouteRouteChildren = {
  IntranetEquipmentRouteRoute: IntranetEquipmentRouteRouteWithChildren,
  IntranetBrandsRoute: IntranetBrandsRoute,
  IntranetCategoriesRoute: IntranetCategoriesRoute,
  IntranetCustomersRoute: IntranetCustomersRoute,
  IntranetMaintenanceRoute: IntranetMaintenanceRoute,
  IntranetOrdersRoute: IntranetOrdersRoute,
  IntranetPortalTextsRoute: IntranetPortalTextsRoute,
  IntranetUsersRoute: IntranetUsersRoute,
  IntranetWarehousesRoute: IntranetWarehousesRoute,
  IntranetIndexRoute: IntranetIndexRoute,
}

const IntranetRouteRouteWithChildren = IntranetRouteRoute._addFileChildren(
  IntranetRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalCartRoute: typeof PortalCartRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalCartRoute: PortalCartRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntranetRouteRoute: IntranetRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
