using Microsoft.EntityFrameworkCore;

namespace GearHub.Api.Data;

public static class LoginEventBootstrap
{
    public static void EnsureLoginEvents(ApplicationDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw(
            """
            CREATE TABLE IF NOT EXISTS "LoginEvents" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" integer NULL,
                "Email" character varying(256) NOT NULL,
                "LoggedInAtUtc" timestamp with time zone NOT NULL,
                "Success" boolean NOT NULL,
                "IpAddress" character varying(64) NULL,
                CONSTRAINT "PK_LoginEvents" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_LoginEvents_AspNetUsers_UserId" FOREIGN KEY ("UserId")
                    REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
            );
            """);
        dbContext.Database.ExecuteSqlRaw(
            """
            CREATE INDEX IF NOT EXISTS "IX_LoginEvents_LoggedInAtUtc"
                ON "LoginEvents" ("LoggedInAtUtc");
            """);
        dbContext.Database.ExecuteSqlRaw(
            """
            CREATE INDEX IF NOT EXISTS "IX_LoginEvents_UserId"
                ON "LoginEvents" ("UserId");
            """);
    }
}
