using Microsoft.EntityFrameworkCore;

namespace GearHub.Api.Data;

public static class PortalTextBootstrap
{
    public static void EnsurePortalTexts(ApplicationDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw(
            """
            CREATE TABLE IF NOT EXISTS "PortalTexts" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Key" character varying(120) NOT NULL,
                "Title" character varying(300) NOT NULL,
                "PlacementHint" character varying(500) NOT NULL DEFAULT '',
                "BodyHtml" text NOT NULL DEFAULT '',
                "SortOrder" integer NOT NULL DEFAULT 0,
                "UpdatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_PortalTexts" PRIMARY KEY ("Id")
            );
            """);
        dbContext.Database.ExecuteSqlRaw(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PortalTexts_Key" ON "PortalTexts" ("Key");
            """);

        var now = DateTime.UtcNow;
        Seed(
            dbContext,
            "catalog.hero.title",
            "Catalog page heading",
            "Top heading on the public equipment catalog (/portal).",
            "Equipment catalog",
            10,
            now);
        Seed(
            dbContext,
            "catalog.hero.subtitle",
            "Catalog page intro",
            "Subtitle under the catalog heading on /portal.",
            "Browse rental equipment. Filter by category or search by name or brand.",
            20,
            now);
        Seed(
            dbContext,
            "catalog.featured.fallback",
            "Featured card blurb (fallback)",
            "Shown on featured catalog cards when an item has no custom description.",
            "<p>Available for rent at a daily rate. Add to your cart to reserve dates.</p>",
            30,
            now);
        Seed(
            dbContext,
            "cart.empty.title",
            "Empty cart heading",
            "Title when the order builder cart has no items (/portal/cart).",
            "Your cart is empty",
            40,
            now);
        Seed(
            dbContext,
            "cart.empty.body",
            "Empty cart message",
            "Description under the empty cart heading.",
            "Browse the catalog and add equipment to start a rental order.",
            50,
            now);
        Seed(
            dbContext,
            "news.list.title",
            "News page heading",
            "Main title on the public news list (/portal/news).",
            "News",
            60,
            now);
        Seed(
            dbContext,
            "news.list.subtitle",
            "News page intro",
            "Subtitle on the public news list.",
            "Updates, tips, and announcements from our team.",
            70,
            now);
    }

    private static void Seed(
        ApplicationDbContext dbContext,
        string key,
        string title,
        string placementHint,
        string bodyHtml,
        int sortOrder,
        DateTime updatedAtUtc)
    {
        dbContext.Database.ExecuteSqlInterpolated(
            $"""
            INSERT INTO "PortalTexts" ("Key", "Title", "PlacementHint", "BodyHtml", "SortOrder", "UpdatedAtUtc")
            VALUES ({key}, {title}, {placementHint}, {bodyHtml}, {sortOrder}, {updatedAtUtc})
            ON CONFLICT ("Key") DO NOTHING;
            """);
    }
}
